# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Vinver, Inc.

[meta]
id = "Aventen_S3_Sync"
family = "Aventen_S3_Sync"
description = "ESP32-S3 board with primary/secondary I2C, primary SPI, a user UART, onboard RGB data pin, ambient light sensor input, and an RF switch control pin."
chip = "esp32s3"
flash_size = "16MB"
psram = false
tier = "volume"
manifest_version = "1.0"
min_runtime_version = "1.0"

[capabilities]
button = {pin = "system.button_pin", type = "button"}
neopixel = {driver = "drivers.neopixel", type = "rgb_led"}
als = {driver = "custom.als", type = "custom"}
rf_switch = {driver = "custom.rf_switch", type = "custom"}

[system]
led_pin = -1
button_pin = 0
reserved_pins = [26, 27, 28, 29, 30, 31, 32]

[system.i2c]
sda = 2
scl = 3
freq = 400000

[system.spi]
mosi = 11
miso = 13
sck = 12

[system.uart]
tx = 43
rx = 44
baud = 115200

[system.i2c1]
sda = 20
scl = 21
freq = 400000

["drivers.neopixel"]
type = "unknown"
pin = 38
num_leds = 1

["custom.als"]
type = "ambient_light_sensor"
als = 17

["custom.rf_switch"]
type = "rf_switch_control"
sw = 37
