# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Vinver, Inc.

[meta]
id = "Bee_Data_Logger"
family = "bee_data_logger"
description = "ESP32-S3 data logger board with primary UART, I2C, SPI, battery/USB power sensing, and an onboard RGB (NeoPixel-compatible) LED with power control."
chip = "esp32s3"
flash_size = "8MB"
psram = false
tier = "volume"
manifest_version = "1.0"
min_runtime_version = "1.0"

[capabilities]
button = {pin = "system.button_pin", type = "button"}
neopixel = {driver = "drivers.neopixel", type = "rgb_led"}
board_specific = {driver = "custom.board_specific", type = "custom"}

[system]
led_pin = -1
button_pin = 0
reserved_pins = [26, 27, 28, 29, 30, 31, 32]

[system.i2c]
sda = 37
scl = 36
freq = 400000

[system.spi]
mosi = 46
miso = 45
sck = 48

[system.uart]
tx = 43
rx = 44
baud = 115200

[system.power]
battery_adc = 1
vbus_sense = 2

["drivers.neopixel"]
type = "ws2812"
pin = 40
power_pin = 34
num_leds = 1

["custom.board_specific"]
type = "misc"
ldo2 = 34
